### ISSUE TITLE
License for reusing XQuery.tmLanguage in another project.

### ISSUE THREAD

**Issue by adamretter** [textmate/xquery.tmbundle#1]
We (myself and @ccheraa) would like to reuse your file https://github.com/textmate/xquery.tmbundle/blob/master/Syntaxes/XQuery.tmLanguage inside the grammars provided with Theia IDE - https://github.com/theia-ide/theia/tree/master/packages/textmate-grammars

However, when contributing a grammar to Theia, we have to declare the license of the grammar. I read the statement in your Readme about licensing. However the exact type of the license remains unknown to me, I have two questions:

1) Is this effectively public domain?
2) I think your license terms do not restrict us from offering the code under a liberal license such as BSD. Is that correct?

**Comment by infininight** [comment]
Not sure what the license is technically called though I think it was copied verbatim from one. But it would be compatible with the BSD license. In a case like this you could just add the original license in the file under a comment in the grammar plist, etc.
